[package]
	name = "fuhaha_rust"
	version = "0.1.0"

[lib]
	path = "src/lib.rs"
	crate-type = ["cdylib"]

[dependencies]
	js-sys = "0.3.36"
	wasm-bindgen = "0.2.59"

[dependencies.web-sys]
	version = "0.3.4"
	features = [
		'Window',
	]
